# Generated by Django 6.0.5 on 2026-05-17 11:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_alerts_enabled', models.BooleanField(default=True)),
                ('dashboard_alerts_enabled', models.BooleanField(default=True)),
                ('alert_on_undercut', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='alert_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProductSKU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('pid', models.CharField(db_index=True, max_length=100)),
                ('lid', models.CharField(max_length=100)),
                ('target_url', models.URLField(blank=True, max_length=1024)),
                ('base_cost', models.DecimalField(decimal_places=2, help_text="Seller's actual cost", max_digits=10)),
                ('floor_price', models.DecimalField(decimal_places=2, help_text='Minimum allowable selling price', max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('last_fetched_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracked_skus', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Product SKU',
                'verbose_name_plural': 'Product SKUs',
                'unique_together': {('user', 'pid')},
            },
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('UNDERCUT', 'Competitor Undercut'), ('BUYBOX_LOST', 'Buy Box Lost'), ('ERROR', 'Fetch Error')], max_length=20)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('product_sku', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tracker.productsku')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CompetitorPriceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_name', models.CharField(db_index=True, max_length=255)),
                ('seller_id', models.CharField(blank=True, max_length=100)),
                ('seller_rating', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('final_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mrp', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('has_buybox', models.BooleanField(default=False, help_text='Did this seller win the Buy Box at fetch time?')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('product_sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_logs', to='tracker.productsku')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['product_sku', '-timestamp'], name='tracker_com_product_49c632_idx')],
            },
        ),
    ]
