# Generated by Django 6.0 on 2026-06-20 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertsetting',
            name='my_seller_name',
            field=models.CharField(blank=True, help_text='Your store name on Flipkart (case-insensitive)', max_length=255, null=True),
        ),
    ]
