# Generated by Django 6.0 on 2026-06-20 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_alertsetting_my_seller_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertsetting',
            name='bg_job_frequency',
            field=models.PositiveIntegerField(default=24, help_text='Background job frequency in hours'),
        ),
    ]
