# Generated by Django 6.0 on 2026-06-20 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_alertsetting_bg_job_frequency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertsetting',
            name='bg_job_frequency',
            field=models.PositiveIntegerField(blank=True, default=24, help_text='Background job frequency in hours', null=True),
        ),
    ]
