# Generated by Django 6.0 on 2026-06-21 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_alter_alertsetting_bg_job_frequency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsku',
            name='base_cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Seller's actual cost", max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='productsku',
            name='floor_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Minimum allowable selling price', max_digits=10, null=True),
        ),
    ]
